import React from 'react';
import { Clock, Calendar, AlertCircle, Download, ExternalLink } from 'lucide-react';
import { DocumentDeadline } from '../types';
import { UIStrings } from '../data/translations';

interface DeadlinesDetectorProps {
  deadlines: DocumentDeadline[];
  ui?: UIStrings;
}

export const DeadlinesDetector: React.FC<DeadlinesDetectorProps> = ({ deadlines, ui }) => {
  if (!deadlines || deadlines.length === 0) return null;

  const handleDownloadICS = (dl: DocumentDeadline) => {
    // Generate simple ICS calendar event
    const now = new Date();
    const daysToAdd = dl.suggestedCalendarDays || 14;
    const eventDate = new Date(now.getTime() + daysToAdd * 24 * 60 * 60 * 1000);
    const dateStr = eventDate.toISOString().replace(/-|:|\.\d\d\d/g, '').substring(0, 15) + 'Z';

    const icsContent = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Jargon Breaker//Document Deadline//EN',
      'BEGIN:VEVENT',
      `SUMMARY:⏰ DEADLINE: ${dl.title}`,
      `DESCRIPTION:Timeframe: ${dl.timeframe}\\nTrigger: ${dl.exactTrigger}\\nConsequence if missed: ${dl.consequenceIfMissed}\\nGenerated by Jargon Breaker`,
      `DTSTART:${dateStr}`,
      `DTEND:${dateStr}`,
      'STATUS:CONFIRMED',
      'END:VEVENT',
      'END:VCALENDAR'
    ].join('\r\n');

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `deadline-${dl.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const getGoogleCalendarUrl = (dl: DocumentDeadline) => {
    const title = encodeURIComponent(`⏰ DEADLINE: ${dl.title}`);
    const details = encodeURIComponent(
      `Notice requirement: ${dl.timeframe}\nTrigger: ${dl.exactTrigger}\nConsequence: ${dl.consequenceIfMissed}\nDecoded by Jargon Breaker`
    );
    return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}`;
  };

  return (
    <div className="bg-amber-50/70 rounded-2xl border border-amber-200/90 shadow-xs p-4 sm:p-6 mb-6">
      <div className="flex items-center gap-2 mb-3">
        <span className="p-1.5 rounded-lg bg-amber-500 text-white">
          <Clock className="w-4 h-4" />
        </span>
        <h3 className="text-base sm:text-lg font-extrabold text-amber-950 font-sans">
          {ui?.deadlineTitle || 'Deadline Detector'} ({deadlines.length})
        </h3>
      </div>
      <p className="text-xs sm:text-sm text-amber-800/90 mb-4">
        {ui?.deadlinesSubtitle || 'Missing legal notice windows or appeal dates can waive your rights. Calendar these critical deadlines:'}
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {deadlines.map((dl) => (
          <div
            key={dl.id}
            className="p-3.5 bg-white rounded-xl border border-amber-200 shadow-2xs flex flex-col justify-between"
          >
            <div>
              <div className="flex items-center justify-between gap-2 mb-1.5">
                <span className="text-xs font-bold text-slate-900">{dl.title}</span>
                <span className="text-[11px] font-bold px-2 py-0.5 rounded-md bg-rose-100 text-rose-800 border border-rose-200">
                  ⏰ {dl.timeframe}
                </span>
              </div>
              <p className="text-xs text-slate-600 italic mb-2 line-clamp-2">
                "{dl.exactTrigger}"
              </p>
              <div className="text-[11px] text-rose-700 bg-rose-50/80 p-2 rounded-lg border border-rose-100 flex items-start gap-1.5">
                <AlertCircle className="w-3.5 h-3.5 shrink-0 mt-0.5 text-rose-600" />
                <span>
                  <strong>{ui?.riskIfMissed || 'Risk if missed:'}</strong> {dl.consequenceIfMissed}
                </span>
              </div>
            </div>

            <div className="flex items-center gap-2 mt-3 pt-2.5 border-t border-slate-100">
              <a
                href={getGoogleCalendarUrl(dl)}
                target="_blank"
                rel="noopener noreferrer"
                className="flex-1 inline-flex items-center justify-center gap-1 px-2.5 py-1 text-[11px] font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors border border-slate-200"
              >
                <Calendar className="w-3 h-3 text-indigo-600" />
                <span>{ui?.googleCal || 'Google Calendar'}</span>
                <ExternalLink className="w-2.5 h-2.5 opacity-60" />
              </a>

              <button
                type="button"
                onClick={() => handleDownloadICS(dl)}
                className="inline-flex items-center justify-center gap-1 px-2.5 py-1 text-[11px] font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors border border-slate-200"
                title="Download .ics event file"
              >
                <Download className="w-3 h-3 text-slate-600" />
                <span>{ui?.icsFile || '.ICS File'}</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
